# Generated by Django 5.2.11 on 2026-02-20 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0780_delete_pushdevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realmplayground",
            name="pygments_language",
            field=models.CharField(
                db_index=True,
                max_length=40,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid characters", regex="^[a-zA-Z0-9_+-./#]+$"
                    )
                ],
            ),
        ),
    ]
